
volumes:
    app_config: 
    app_logs:
    app_pictures: 

services:

    bitbot:
        image: ghcr.io/donbing/bitbot:latest
        privileged: true
        restart: unless-stopped
        network_mode: "host" # alows us to show IP address
        volumes:
            - app_config:/code/config:rw
            - app_logs:/code/logs:rw
            - app_pictures:/code/pictures:rw
            - /etc/localtime:/etc/localtime:ro # share timezone with the pi
        #environment:
        #    - BITBOT_OUTPUT=disk, waveshare.epd2in7b_V2, inky
    
    config-editor:
        image: ghcr.io/donbing/bitbot-config-server:latest
        restart: unless-stopped
        volumes:
            - app_config:/code/config:rw
            - app_logs:/code/logs:rw
            - app_pictures:/code/pictures:rw
        ports:
            - "8080:8080"
            
    # display-driver:
    #     platform: linux/arm64/v7
    #     restart: unless-stopped
    #     build:  
    #         dockerfile: display-driver.dockerfile
    #         context: .
    #     volumes:
    #         - app_config:/code/config:rw
    #         - app_logs:/code/logs:rw
    #         - app_pictures:/code/pictures:rw
    #     ports:
    #         - 8076:8080