
volumes:
    app_config: 
    app_logs:
    app_pictures: 

services:

    bitbot:
        platform: linux/arm64/v7
        privileged: true
        restart: unless-stopped
        build: 
            dockerfile: bitbot.dockerfile
            context: .
        volumes:
            - app_config:/code/config:rw
            - app_logs:/code/logs:rw
            - app_pictures:/code/pictures:rw
        #environment:
        #    - BITBOT_OUTPUT=disk, waveshare.epd2in7b_V2, inky
    
    config-editor:
        platform: linux/arm64/v7
        restart: unless-stopped
        build:  
            dockerfile: config-server.dockerfile
            context: .
        volumes:
            - app_config:/code/config:rw
            - app_logs:/code/logs:rw
            - app_pictures:/code/pictures:rw
        ports:
            - "8080:8080"
            
    # display-driver:
    #     platform: linux/arm64/v7
    #     restart: unless-stopped
    #     build:  
    #         dockerfile: display-driver.dockerfile
    #         context: .
    #     volumes:
    #         - app_config:/code/config:rw
    #         - app_logs:/code/logs:rw
    #         - app_pictures:/code/pictures:rw
    #     ports:
    #         - 8076:8080