version: "2.1"

services:

    bit-bot:
        image: ghcr.io/donbing/bitbot:main
        privileged: true
        restart: unless-stopped

    # config-editor:
    #     build: ./docker/config-editor.dockerfile