version: "2.1"

services:

    wifi-connect:
        image: balenablocks/wifi-connect:rpi
        network_mode: "host"
        restart: unless-stopped
        labels:
            io.balena.features.dbus: '1'
        cap_add:
            - NET_ADMIN
        environment:
            DBUS_SYSTEM_BUS_ADDRESS: "unix:path=/host/run/dbus/system_bus_socket"

    bit-bot:
        image: ghcr.io/donbing/bitbot:main
        privileged: true
        restart: unless-stopped

    # config-editor:
    #     build: ./docker/config-editor.dockerfile