FROM navikey/raspbian-bullseye:latest

RUN apt update && \
    apt install -y \
    --no-install-recommends \
    python3-pip \
    && rm -rf /var/lib/apt/lists/* 

COPY requirements.txt .
RUN pip3 install --user --prefer-binary --no-cache-dir -r requirements.txt

WORKDIR /code
COPY . .

CMD [ "python3", "__main__.py" ]